@startuml
actor User
actor Admin

left to right direction

rectangle "Library Management System" {
  (Enter User Information)
  (Borrow Book)
  (Return Book)
  (Search Book)
  (View Borrowing History)
  (Add/Update/Remove Book)
  (Admin Login)
  (View System Logs)
}

User --> (Enter User Information)
User --> (Borrow Book)
User --> (Return Book)
User --> (Search Book)
User --> (View Borrowing History)

Admin --> (Add/Update/Remove Book)
Admin --> (Admin Login)
Admin --> (View System Logs)

@enduml

